global:
  scrape_interval: 15s  # Intervalo de tempo entre as coletas de métricas

scrape_configs:
  - job_name: 'microsservicos'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['service-cliente:8080', 'service-produto:8081']  